trigger:
  branches:
    include:
      - main

pool:
  name: CloudAgentPool  # your custom self-hosted agent

variables:
  NODE_VERSION: '18.x'

stages:
  - stage: BuildAndTest
    displayName: "Build and Test"
    jobs:
      - job: Build
        displayName: "Install and Build"
        steps:
          # Checkout the code
          - checkout: self

          # Use Node.js 18.x
          - task: NodeTool@0
            inputs:
              versionSpec: '$(NODE_VERSION)'
            displayName: "Use Node.js $(NODE_VERSION)"

          # Install dependencies
          - script: npm ci
            displayName: "Install Dependencies"

          # Build project
          - script: npm run build
            displayName: "Build Project"

          # Dummy test (safe for your setup)
          - script: npm test || echo 'No tests defined'
            displayName: "Run Tests"

          # Simulated deployment
          - script: echo "✅ Deployment successful (simulated)"
            displayName: "Deploy App"
