trigger:
  branches:
    include:
      - main

pool:
  name: CloudAgentPool

variables:
  NODE_VERSION: '22.x'

stages:
  - stage: BuildAndTest
    displayName: "Build and Test"
    jobs:
      - job: Build
        displayName: "Install and Build"
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '$(NODE_VERSION)'
            displayName: "Use Node.js $(NODE_VERSION)"

          - script: npm install
            displayName: "Install Dependencies"

          - script: npm run build
            displayName: "Build Project"

          - script: npm test || echo 'No tests defined'
            displayName: "Run Tests"

          - script: echo "✅ Deployment successful (simulated)"
            displayName: "Deploy App"
