name: "OWASP ZAP Baseline Scan"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # every Monday 6 AM UTC

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://cloudteam18stark.azurewebsites.net'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -J zap_output.json -w zap_output.html'
          allow_issue_writing: false
          artifact_name: 'zap-report'    # ✅ fixed (no underscore)
          issue_title: 'OWASP ZAP Baseline Scan Results'

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report               # ✅ match above
          path: |
            zap_output.html
            zap_output.json
